---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: pets
  labels:
    app: logstash-config
data:
  logstash.yml: |-
    xpack:
      monitoring:
        enabled: true
        elasticsearch.url: http://elasticsearch:9200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-pipeline
  namespace: pets
  labels:
    app: logstash
data:
  input_main: |-
    input {
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["filebeat"]
        codec => "json"
        tags => ["filebeat"]
        enable_metric => "true"
        type => "filebeat"
      }
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["packetbeat"]
        codec => "json"
        tags => ["packetbeat"]
        enable_metric => "true"
        type => "log"
        client_id => "packetbeat"
      }
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["auditbeat"]
        codec => "json"
        tags => ["auditbeat"]
        enable_metric => "true"
        type => "log"
        client_id => "auditbeat"
      }
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["heartbeat"]
        codec => "json"
        tags => ["heartbeat"]
        enable_metric => "true"
        type => "log"
        client_id => "heartbeat"
      }
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["metricbeat"]
        codec => "json"
        tags => ["metricbeat"]
        enable_metric => "true"
        type => "log"
        client_id => "metricbeat"
      }

    }
  filter_main: |-
    filter {

      if [topics] == "filebeat" {

          grok {
              match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}%{SPACE}\[%{GREEDYDATA:transaction.id},%{SPACE}%{GREEDYDATA:trace.id}\]%{SPACE}%{LOGLEVEL:level}%{SPACE}%{SPACE}%{INT:tenant_id}%{SPACE}-%{SPACE}-%{SPACE}-%{SPACE}\[(?<thread>[^\]]+)\]%{SPACE}%{JAVACLASS:java_class}%{SPACE}:%{GREEDYDATA:log_message}" }
          }

          kv {
              include_keys => [ "transaction.id", "trace.id" ]
              source => "mdc"
          }

          mutate {
              convert => { "transaction.id" => "string" }
          }
          mutate {
              convert => { "trace.id" => "string" }
          }
      }

    }
  output_main: |-
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
    }