kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master
  namespace: elastic
  labels:
    app: "elasticsearch-master"
spec:
  type: ClusterIP
  selector:
    app: "elasticsearch-master"
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300